id: ADB04C3A0
base_file: fB111.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:15:19.303286
  last_modified_at: 2022-06-17 11:15:19.303289
