id: ADB04C3A0
base_file: f14BA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:15:19.251055
  last_modified_at: 2022-06-17 11:15:19.251064
